AswinDracoDigital-nota-56390bd7f809/Nota/Areas/User/Controllers/UserProductController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nota.Areas.Admin.Models;
using Nota.Areas.User.Interface;
using Nota.Areas.User.Models;
using Nota.Common;
using Nota.Context;
using System;
using System.IO;
using System.Linq;

namespace Nota.Areas.User.Controllers
{
    [Area("User")]
    public class UserProductController : BaseController
    {
        #region Member Declaration
        private readonly IUserProduct _product;
        private readonly ApplicationDbContext _context;
        [Obsolete]
        private readonly IHostingEnvironment _hostingEnvironment;
        #endregion

        #region Constractor
        [Obsolete]
        public UserProductController(IUserProduct product, ApplicationDbContext context, IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
            _product = product;
            _context = context;
        }
        #endregion

        #region Index
        public IActionResult Index()
        {
            var viewModel = new UserProductModel
            {
                ModuleName = new CommonMessagesModel { ModuleName = "Product" }
            };
            return View(viewModel);
        }
        #endregion

        #region Create
        [HttpGet]
        public IActionResult Create()
        {
            UserProductModel productModel = new UserProductModel();
            BindAllDropDown(productModel);
            return View(productModel);
        }

        [HttpPost]
        public IActionResult Create(UserProductModel productModel, AttachmentModel attachmentModel)
        {
            if (_product.IsProductExists(productModel.UserProductID, productModel.Title.Trim()))
            {
                TempData["Msg"] = "alreadyexists";
                BindAllDropDown(productModel);
                return View(productModel);
            }
            //IFormFile file;
            //if (productModel.CategoriesID == 1)
            //{
            //    file =
            //}
            if (attachmentModel.Attachments != null && attachmentModel.Attachments.Count() > 0)
            {
                var attachments = attachmentModel.Attachments.Where(x => x != null).ToList();
            }
            _product.AddProduct(productModel, attachmentModel);
            TempData["Msg"] = "added";
            return RedirectToAction("Index", "UserDashboard");
        }
        #endregion

        #region Bind All Drop Down
        private UserProductModel BindAllDropDown(UserProductModel productModel)
        {
            productModel.SelectCategories = new SelectList(_product.GetCategoriesList(0, string.Empty), "CategoriesID", "Name");
            return productModel;
        }
        #endregion
    }
}

AswinDracoDigital-nota-56390bd7f809/Nota/Areas/User/Views/UserProduct/Create.cshtml
@model Nota.Areas.User.Models.UserProductModel
@using Nota.Areas.User.EnumType
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/User/Views/Shared/_Layout.cshtml";
}
@section style{
    <!-- font -->
    <link href="~/fileuploader/font/font-fileuploader.css" media="all" rel="stylesheet" />
    <!-- css -->
    <link href="~/fileuploader/jquery.fileuploader.min.css" media="all" rel="stylesheet" />
}
<div class="ms_profile_wrapper">
    <h1>Add Product</h1>
    <div class="ms_profile_box">
        <form asp-area="User" asp-action="Create" asp-controller="UserProduct" id="basic-form" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="ms_pro_form">
                @Html.HiddenFor(model => model.PublicUserID)

                <div class="form-group">
                    <label>Title<span class="mandatory"> *</span> </label>
                    <input asp-for="Title" placeholder="Enter Title" type="text" class="form-control parsley-error" required="" data-parsley-id="29">
                    <span asp-validation-for="Title" class="text-white"></span>
                </div>
                <div class="form-group">
                    <label>Description<span class="mandatory"> *</span> </label>
                    <input asp-for="Description" placeholder="Enter Description" type="text" class="form-control parsley-error" required="" data-parsley-id="29">
                    <span asp-validation-for="Description" class="text-white"></span>
                </div>
                <div class="form-group" id="uploadtype">
                    <label>Upload Type<span class="mandatory"> *</span> </label><br />
                    <input id="notes" checked  asp-for="UploadType"  type="radio" value="@((Int16)UploadTypeEnum.Notes)" name="UploadType" data-toggle="switchbutton" tabindex="8"><lab1>  Notes</lab1>
                    <input id="music" asp-for="UploadType"  type="radio" value="@((Int16)UploadTypeEnum.Music)" name="UploadType" data-toggle="switchbutton" tabindex="8"><lab1>  Music</lab1>
                    <input id="lyrics" asp-for="UploadType"  type="radio" value="@((Int16)UploadTypeEnum.Lyrics)" name="UploadType" data-toggle="switchbutton" tabindex="8"><lab1>  Lyrics</lab1>
                    <span asp-validation-for="UploadType" class="text-white"></span>
                </div>
                <div class="form-group">
                    <label>Price Type<span class="mandatory"> *</span> </label><br />
                    <input id="freechkbox" asp-for="PriceType" type="radio" value="@((Int16)PriceTypeEnum.Free)" name="PriceType" data-toggle="switchbutton" data-onlabel="Active" data-offlabel="Inactive" tabindex="8"><lab1>  Free</lab1>
                    <input id="premium" asp-for="PriceType" type="radio" value="@((Int16)PriceTypeEnum.Premium)" name="PriceType" data-toggle="switchbutton" data-onlabel="Active" data-offlabel="Inactive" tabindex="8"><lab1>  Premium</lab1><br />
                    <span asp-validation-for="PriceType" class="text-white"></span>
                </div>
                <div class="form-group">
                    <label>Categories <span class="mandatory"> *</span> </label>
                    <select asp-for="CategoriesID" asp-items="Model.SelectCategories" class="form-control parsley-error" tabindex="7">
                        <option value="">-- Select Categories --</option>
                    </select>
                </div>
                <div class="form-group" id="discount">
                    <label>Discount Percentage<span class="mandatory"></span> </label>
                    <input asp-for="DiscountPercentage" placeholder="Enter Discount Percentage" type="text" class="form-control parsley-error" id="discount" data-parsley-id="29">
                </div>
                <div class="form-group" id="amount">
                    <label>Amount<span class="mandatory"> *</span> </label>
                    <input asp-for="Amount" placeholder="Enter Amount" type="number" id="amount" class="form-control parsley-error" data-parsley-id="29">
                    <span asp-validation-for="Amount" class="text-danger"></span>
                </div>
                <div class=" form-group"></div>
                <div class="form-group" id="dvFileUpload">
                    <input type="file" id="Notes" name="Attachments" class="files" />
                    <input type="file" id="Mp3" name="Attachments" class="files" />
                    <input type="file" id="Lyrics" name="Attachments" class="files" />
                </div>
                <div class=" form-group"></div>
                <div class="form-group">
                    <button type="submit" style="text-align:center;" class="ms_btn">Save</button>
                    <button type="button" onclick="window.location='/User/UserDashboard'" class="ms_btn" title="Save">Back</button>
                </div>
            </div>
        </form>
    </div>
</div>
@section scripts
{   
    <script src="~/fileuploader/jquery.fileuploader.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        window.onload = function () {
                $("#dvFileUpload").children(":last").hide();
                $("#dvFileUpload").children(":nth-child(2)").hide();
        }
        $(document).ready(function () {
           
            if ('@Html.TempData["Msg"]' == "alreadyexists") {
                swal("Oops!", "Product already exists.", "warning");
            }
            if ('@Html.TempData["Msg"]' == "changed") {
                swal("Changed!", "Your password has been changed successfully.", "success");
            }
            if ('@Html.TempData["Msg"]' == "welcome") {
                swal("Welcome!", "Nota music player.", "success");
            }
            $("#notes").click(function () {
                if ($(this).is(":checked")) {
                    $("#dvFileUpload").children(":last").find(".fileuploader-items-list").empty();
                    $("#dvFileUpload").children(":last").find(".fileuploader-input-caption").html("<span>Choose files to upload</span>");
                    $("#dvFileUpload").children(":last").children("input")[0].value = "";
                    $("#dvFileUpload").children(":last").hide();

                    $("#dvFileUpload").children(":nth-child(2)").find(".fileuploader-items-list").empty();
                    $("#dvFileUpload").children(":nth-child(2)").find(".fileuploader-input-caption").html("<span>Choose files to upload</span>");
                    $("#dvFileUpload").children(":nth-child(2)").children("input")[0].value = "";
                    $("#dvFileUpload").children(":nth-child(2)").hide();

                    $("#dvFileUpload").children(":first").show();
                }
            });
            $("#music").click(function () {
                if ($(this).is(":checked")) {

                    $("#dvFileUpload").children(":first").find(".fileuploader-items-list").empty();
                    $("#dvFileUpload").children(":first").find(".fileuploader-input-caption").html("<span>Choose files to upload</span>");
                    $("#dvFileUpload").children(":first").children("input")[0].value = "";
                    $("#dvFileUpload").children(":first").hide();

                    $("#dvFileUpload").children(":last").find(".fileuploader-items-list").empty();
                    $("#dvFileUpload").children(":last").find(".fileuploader-input-caption").html("<span>Choose files to upload</span>");
                    $("#dvFileUpload").children(":last").children("input")[0].value = "";
                    $("#dvFileUpload").children(":last").hide();

                    $("#dvFileUpload").children(":nth-child(2)").show();
                }
            });
            $("#lyrics").click(function () {
                if ($(this).is(":checked")) {
                    $("#dvFileUpload").children(":first").hide();
                    $("#dvFileUpload").children(":first").find(".fileuploader-items-list").empty();
                    $("#dvFileUpload").children(":first").find(".fileuploader-input-caption").html("<span>Choose files to upload</span>");
                    $("#dvFileUpload").children(":first").children("input")[0].value = "";

                    $("#dvFileUpload").children(":nth-child(2)").hide();
                    $("#dvFileUpload").children(":nth-child(2)").find(".fileuploader-items-list").empty();
                    $("#dvFileUpload").children(":nth-child(2)").find(".fileuploader-input-caption").html("<span>Choose files to upload</span>");
                    $("#dvFileUpload").children(":nth-child(2)").children("input")[0].value = "";

                    $("#dvFileUpload").children(":last").show();
                }
            });
            // Hide Show Amount & Discount
            $("#freechkbox").click(function () {
                if ($(this).is(":checked")) {
                    $("#amount").hide();
                    $("#discount").hide();
                }
            });
            $("#premium").click(function () {
                if ($(this).is(":checked")) {
                    $("#amount").show();
                    $("#discount").show();
                }
            });

            $('input[id="Notes"]').fileuploader({
                inputNameBrackets: false,
                limit: 10,
                maxSize: 5,
                extensions: ['jpeg','png','jpg'],
                addMore: true,
                thumbnails: {
                    onImageLoaded: function (item) {
                        if (!item.html.find('.fileuploader-action-edit').length)
                            item.html.find('.fileuploader-action-remove').before('<button type="button" class="fileuploader-action fileuploader-action-popup fileuploader-action-edit" title="Edit"><i class="fileuploader-icon-edit"></i></button>');
                    }
                },
                editor: {
                    cropper: {
                        ratio: '1:1',
                        minWidth: 100,
                        minHeight: 100,
                        showGrid: true
                    }
                }       

            });
            $('input[id="Mp3"]').fileuploader({
                inputNameBrackets: false,
                limit: 1,
                maxSize: 10,
                extensions: ['mp3'],
                addMore: true,
                thumbnails: {
                    onImageLoaded: function (item) {
                        if (!item.html.find('.fileuploader-action-edit').length)
                            item.html.find('.fileuploader-action-remove').before('<button type="button" class="fileuploader-action fileuploader-action-popup fileuploader-action-edit" title="Edit"><i class="fileuploader-icon-edit"></i></button>');
                    }
                }  
            });

            $('input[id="Lyrics"]').fileuploader({
                inputNameBrackets: false,
                limit: 1,
                maxSize: 10,
                extensions: ['pdf'],
                addMore: true,
                thumbnails: {
                    onImageLoaded: function (item) {
                        if (!item.html.find('.fileuploader-action-edit').length)
                            item.html.find('.fileuploader-action-remove').before('<button type="button" class="fileuploader-action fileuploader-action-popup fileuploader-action-edit" title="Edit"><i class="fileuploader-icon-edit"></i></button>');
                    }
                } 
            });
        });
    </script>
}

AswinDracoDigital-nota-56390bd7f809/Nota/Areas/User/Views/UserProduct/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/User/Views/Shared/_Layout.cshtml";
}